import requests, json, uuid

leads = [
  {"business":"Rodriguez & Partners Law","owner":"Carlos Rodriguez","phone":"(305) 891-2234","email":"info@rodriguezpartners.com","industry":"Law Firm","address":"1221 Brickell Ave, Miami FL","notes":"Pitch: AI answers every client call 24/7, books consults automatically. Never miss a case lead."},
  {"business":"Perez Legal Group","owner":"Maria Perez","phone":"(305) 443-7890","email":"contact@perezlegal.com","industry":"Law Firm","address":"2525 Coral Way, Miami FL","notes":"Pitch: AI receptionist handles after-hours calls — biggest missed-lead killer for law firms."},
  {"business":"Gutierrez Family Law","owner":"Luis Gutierrez","phone":"(786) 334-5521","email":"lgutierrez@familylawfl.com","industry":"Law Firm","address":"7300 N Kendall Dr, Miami FL","notes":"Pitch: Automate intake calls, never lose a client to voicemail."},
  {"business":"Coral Gables Injury Attorneys","owner":"Sandra Vega","phone":"(305) 567-4412","email":"svega@cginjury.com","industry":"Law Firm","address":"169 Miracle Mile, Coral Gables FL","notes":"Pitch: Personal injury firms get flooded with calls. AI handles triage 24/7."},
  {"business":"Morales & Cruz Law","owner":"Roberto Morales","phone":"(305) 774-9983","email":"rm@moralescruz.com","industry":"Law Firm","address":"3250 Mary St, Coconut Grove FL","notes":"Pitch: AI receptionist, appointment booking, client follow-up automation."},
  {"business":"Miami Immigration Law","owner":"Eduardo Varela","phone":"(305) 358-9900","email":"evarela@miamiimmigration.com","industry":"Law Firm","address":"25 SE 2nd Ave, Miami FL","notes":"Pitch: Immigration clients call urgently. AI answers in English and Spanish 24/7."},
  {"business":"Coconut Grove Law Office","owner":"Rebecca Stone","phone":"(305) 448-3322","email":"rstone@cglaw.com","industry":"Law Firm","address":"2800 SW 27th Ave, Miami FL","notes":"Pitch: Clients in legal trouble call urgently. AI answers and books consultations 24/7."},
  {"business":"South Miami Dental Center","owner":"Dr. Ana Lopez","phone":"(305) 661-8820","email":"info@smdentalcenter.com","industry":"Dental Office","address":"5975 Sunset Dr, South Miami FL","notes":"Pitch: Dental offices lose 30% of new patients to unanswered calls. AI books appointments 24/7."},
  {"business":"Brickell Smiles Dentistry","owner":"Dr. James Kim","phone":"(305) 373-2299","email":"hello@brickellsmiles.com","industry":"Dental Office","address":"801 Brickell Key Dr, Miami FL","notes":"Pitch: AI handles appointment requests even when your front desk is slammed."},
  {"business":"Westchester Pediatric Dental","owner":"Dr. Monica Suarez","phone":"(305) 261-7733","email":"msuarez@westchesterpeddent.com","industry":"Dental Office","address":"8765 SW 24th St, Miami FL","notes":"Pitch: Parents call for sick kids at all hours. AI triages and books."},
  {"business":"South Miami Orthodontics","owner":"Dr. Brian Chang","phone":"(305) 667-1100","email":"bchang@smortho.com","industry":"Dental Office","address":"5840 S Dixie Hwy, South Miami FL","notes":"Pitch: Ortho practices have huge call volume. AI handles new patient intake."},
  {"business":"Coral Way Dentistry","owner":"Dr. Anna Reyes","phone":"(305) 285-9977","email":"areyes@coralwaydentistry.com","industry":"Dental Office","address":"3155 Coral Way, Miami FL","notes":"Pitch: Front desk can't answer while with patients. AI picks up every call."},
  {"business":"Palmetto Bay Dental","owner":"Dr. Ray Gomez","phone":"(786) 293-3322","email":"rgomez@palmettodental.com","industry":"Dental Office","address":"7300 SW 152nd St, Miami FL","notes":"Pitch: Family dental practices depend on new patient calls. AI converts every inquiry."},
  {"business":"Homestead Dental Care","owner":"Dr. Jose Mendez","phone":"(305) 245-8822","email":"jmendez@homesteaddental.com","industry":"Dental Office","address":"28 N Krome Ave, Homestead FL","notes":"Pitch: Rural dental practices miss calls constantly. AI covers 24/7."},
  {"business":"Kendall Family Medicine","owner":"Dr. Patricia Ruiz","phone":"(305) 274-1100","email":"office@kendallfamilymed.com","industry":"Medical Office","address":"11200 SW 8th St, Miami FL","notes":"Pitch: Free your front desk from call overflow. AI takes patient info and books slots."},
  {"business":"Aventura Urgent Care","owner":"Dr. Sarah Chen","phone":"(305) 933-5544","email":"info@aventuraurgentcare.com","industry":"Medical Office","address":"2950 Aventura Blvd, Aventura FL","notes":"Pitch: Urgent care runs 24/7 — your phone system should too."},
  {"business":"Hialeah Pediatric Associates","owner":"Dr. Carmen Diaz","phone":"(305) 558-3311","email":"cdiaz@hialeahpeds.com","industry":"Medical Office","address":"1990 W 49th St, Hialeah FL","notes":"Pitch: Worried parents call at all hours. AI answers and routes to on-call staff."},
  {"business":"Coral Gables Eye Care","owner":"Dr. David Park","phone":"(305) 442-6789","email":"dpark@cgeyecare.com","industry":"Medical Office","address":"280 Miracle Mile, Coral Gables FL","notes":"Pitch: Book eye exams automatically. AI handles new patient intake."},
  {"business":"Miami Beach Dermatology","owner":"Dr. Lisa Fernandez","phone":"(305) 538-8822","email":"lfernandez@mbderm.com","industry":"Medical Office","address":"1000 Collins Ave, Miami Beach FL","notes":"Pitch: High-volume cosmetic calls need fast response. AI qualifies and books."},
  {"business":"Kendall Urgent Care","owner":"Dr. Chris Brown","phone":"(305) 273-9988","email":"cbrown@kendallurgent.com","industry":"Medical Office","address":"12851 SW 42nd St, Miami FL","notes":"Pitch: Urgent care volume is unpredictable. AI handles call overflow so staff stay focused."},
  {"business":"Brickell Acupuncture","owner":"Dr. Wei Zhang","phone":"(305) 373-7755","email":"wzhang@brickellacupuncture.com","industry":"Medical Office","address":"70 SW 10th St, Miami FL","notes":"Pitch: Wellness practices grow on word-of-mouth referral calls. AI never misses them."},
  {"business":"Doral Chiropractic & Wellness","owner":"Dr. Michael Torres","phone":"(305) 594-7700","email":"mtorres@doralchiro.com","industry":"Chiropractic","address":"8300 NW 53rd St, Doral FL","notes":"Pitch: New patient calls are gold. AI captures every one and books same-day."},
  {"business":"Palmetto Bay Chiropractic","owner":"Dr. Luis Soto","phone":"(786) 293-5511","email":"lsoto@palmettochiro.com","industry":"Chiropractic","address":"16360 SW 88th St, Miami FL","notes":"Pitch: New patient calls are your growth engine. AI captures every single one."},
  {"business":"Miami Spine & Wellness","owner":"Dr. Kevin Park","phone":"(786) 347-8899","email":"kpark@miamispine.com","industry":"Chiropractic","address":"7310 SW 8th St, Miami FL","notes":"Pitch: New patient calls are gold. AI captures every one and books same-day."},
  {"business":"Westchester Physical Therapy","owner":"Marcus Johnson","phone":"(305) 262-4400","email":"mjohnson@westchesterpt.com","industry":"Physical Therapy","address":"8600 Bird Rd, Miami FL","notes":"Pitch: PT clinics depend on referral follow-up calls. AI handles all intake."},
  {"business":"Aventura Physical Therapy","owner":"Dr. Sam Cohen","phone":"(305) 931-4455","email":"scohen@aventurapt.com","industry":"Physical Therapy","address":"21150 Biscayne Blvd, Aventura FL","notes":"Pitch: PT relies on referral follow-up calls. AI handles intake so therapists stay focused."},
  {"business":"Coconut Grove Veterinary","owner":"Dr. Emily Watson","phone":"(305) 444-8811","email":"ewatson@cgvet.com","industry":"Veterinary","address":"3280 SW 22nd St, Miami FL","notes":"Pitch: Pet emergencies happen at 2am. AI answers, triages, routes urgent calls."},
  {"business":"Kendall Animal Hospital","owner":"Dr. Paul Rivera","phone":"(305) 595-7700","email":"privera@kendallanimal.com","industry":"Veterinary","address":"11401 N Kendall Dr, Miami FL","notes":"Pitch: Pet emergencies = urgent calls at any hour. AI triages and routes."},
  {"business":"Miami Luxury Realty","owner":"Isabella Santos","phone":"(305) 864-5500","email":"isantos@miamiluxury.com","industry":"Real Estate","address":"1 SE 3rd Ave, Miami FL","notes":"Pitch: Buyer leads go cold in minutes. AI responds to inquiries instantly, books showings."},
  {"business":"Brickell Property Group","owner":"Jason Rivera","phone":"(786) 220-3300","email":"jrivera@brickellpg.com","industry":"Real Estate","address":"1200 Brickell Ave Ste 800, Miami FL","notes":"Pitch: Never lose a condo buyer lead to a missed call again."},
  {"business":"South Beach Condos","owner":"Diana Montoya","phone":"(305) 672-9988","email":"dmontoya@sbcondos.com","industry":"Real Estate","address":"500 Ocean Dr, Miami Beach FL","notes":"Pitch: International buyers call at odd hours. AI answers in English and Spanish."},
  {"business":"Doral Homes Realty","owner":"Victor Acosta","phone":"(305) 500-7722","email":"vacosta@doralhomes.com","industry":"Real Estate","address":"8180 NW 36th St, Doral FL","notes":"Pitch: AI books property tours automatically from any lead source."},
  {"business":"Coral Gables Estates","owner":"Nicole Hoffman","phone":"(305) 443-2211","email":"nhoffman@cgstates.com","industry":"Real Estate","address":"2333 Ponce De Leon Blvd, Coral Gables FL","notes":"Pitch: Luxury market demands instant response. AI delivers it."},
  {"business":"Miami Estates Realty","owner":"Claire Dubois","phone":"(305) 667-4433","email":"cdubois@miamiestaterealty.com","industry":"Real Estate","address":"4000 S Red Rd, Miami FL","notes":"Pitch: Real estate leads have a 5-minute window. AI responds instantly."},
  {"business":"South Miami Realty Group","owner":"Paul Hernandez","phone":"(305) 666-3311","email":"phernandez@smrealtygroup.com","industry":"Real Estate","address":"5977 Commerce Ln, South Miami FL","notes":"Pitch: Listing inquiries expire in hours. AI responds in seconds."},
  {"business":"Miami Cool Air HVAC","owner":"Tony Alvarez","phone":"(305) 882-6600","email":"talvarez@miamicoolair.com","industry":"HVAC","address":"8200 NW 27th Ave, Miami FL","notes":"Pitch: AC emergencies don't wait. AI answers, books service calls 24/7."},
  {"business":"Miami Lakes HVAC","owner":"Ray Espinoza","phone":"(305) 821-5533","email":"respinoza@miamilakeshvac.com","industry":"HVAC","address":"6265 Miami Lakes Dr, Miami Lakes FL","notes":"Pitch: Summer AC emergencies — AI answers every call when your team is booked."},
  {"business":"North Miami HVAC Solutions","owner":"Danny Ruiz","phone":"(305) 895-6600","email":"druiz@nmhvac.com","industry":"HVAC","address":"1755 NE 149th St, North Miami FL","notes":"Pitch: HVAC runs 24/7. Your phone system should too. AI handles all calls."},
  {"business":"South Florida Plumbing Pro","owner":"Eddie Garcia","phone":"(786) 431-9900","email":"egarcia@sfplumbingpro.com","industry":"Plumbing","address":"2750 W Flagler St, Miami FL","notes":"Pitch: Plumbing emergencies = urgent calls. AI captures every one when you're on a job."},
  {"business":"Miami Lakes Plumbing","owner":"Sam Torres","phone":"(305) 820-4488","email":"storres@miamilakesplumbing.com","industry":"Plumbing","address":"7400 Miami Lakes Dr, Miami Lakes FL","notes":"Pitch: Plumbing emergencies don't wait. AI dispatches your team while you're on a job."},
  {"business":"Kendall Electric Services","owner":"Bob Martinez","phone":"(305) 270-4411","email":"bmartinez@kendallelectric.com","industry":"Electrical","address":"10710 SW 72nd St, Miami FL","notes":"Pitch: Electricians miss calls constantly while on site. AI answers and books."},
  {"business":"Miami Electrical Pros","owner":"Ray Santos","phone":"(305) 638-4422","email":"rsantos@miamielectricalpros.com","industry":"Electrical","address":"3500 NW 27th Ave, Miami FL","notes":"Pitch: Electricians on job sites miss calls constantly. AI captures every service request."},
  {"business":"All Star Roofing Miami","owner":"Frank Delgado","phone":"(305) 662-7733","email":"fdelgado@allstarroofing.com","industry":"Roofing","address":"6601 SW 57th Ave, Miami FL","notes":"Pitch: After storm season, roofing calls spike 10x. AI handles the overflow."},
  {"business":"Hialeah Roofing Solutions","owner":"Pedro Gonzalez","phone":"(305) 557-9922","email":"pgonzalez@hialeahroof.com","industry":"Roofing","address":"1500 W 84th St, Hialeah FL","notes":"Pitch: Post-storm surge — AI handles 10x call volume without adding staff."},
  {"business":"Premier Pool Service","owner":"Steve Lopez","phone":"(305) 251-8844","email":"slopez@premierpool.com","industry":"Pool Service","address":"14155 SW 119th Ave, Miami FL","notes":"Pitch: Pool service companies run lean. AI handles scheduling so techs stay in the field."},
  {"business":"Brickell Auto Repair","owner":"Miguel Ramos","phone":"(305) 854-3322","email":"mramos@brickellautore.com","industry":"Auto Repair","address":"400 SW 8th St, Miami FL","notes":"Pitch: AI books oil changes, estimates, service calls automatically."},
  {"business":"Kendall European Auto","owner":"Chris Schultz","phone":"(305) 279-5511","email":"cschultz@kendalleuropean.com","industry":"Auto Repair","address":"12455 N Kendall Dr, Miami FL","notes":"Pitch: BMW/Mercedes clients expect premium service from first call. AI delivers."},
  {"business":"Doral Auto Center","owner":"Raul Perez","phone":"(305) 591-4400","email":"rperez@doralauto.com","industry":"Auto Repair","address":"3601 NW 82nd Ave, Doral FL","notes":"Pitch: Multi-bay shops get overwhelmed. AI handles call volume while techs work."},
  {"business":"Hialeah Auto Glass","owner":"Hector Ruiz","phone":"(305) 558-2244","email":"hruiz@hialeahautoglass.com","industry":"Auto Repair","address":"3100 W 16th Ave, Hialeah FL","notes":"Pitch: Windshield jobs are high-volume quick calls. AI books same-day appointments."},
  {"business":"Doral Body Shop","owner":"Luis Medina","phone":"(305) 477-3366","email":"lmedina@doralbodyshop.com","industry":"Auto Repair","address":"7200 NW 36th St, Doral FL","notes":"Pitch: Insurance claim calls need fast response. AI handles intake 24/7."},
  {"business":"Miami Beach Auto Detail","owner":"Carlo Ricci","phone":"(305) 532-8811","email":"cricci@mbautodetail.com","industry":"Auto Repair","address":"1100 Alton Rd, Miami Beach FL","notes":"Pitch: Detailing bookings need fast confirmation. AI books while you're in the bay."},
  {"business":"Homestead Auto Repair","owner":"Mike Delgado","phone":"(305) 248-4411","email":"mdelgado@homesteadauto.com","industry":"Auto Repair","address":"101 SE 1st Ave, Homestead FL","notes":"Pitch: Busy shop = missed calls. AI books service appointments all day."},
  {"business":"Aventura Luxury Cars","owner":"Mark Steinberg","phone":"(305) 935-2211","email":"msteinberg@aventuraluxurycars.com","industry":"Auto Dealer","address":"19600 Biscayne Blvd, Aventura FL","notes":"Pitch: Car buyer leads expire fast. AI responds to inquiries within seconds."},
  {"business":"Brickell Beauty Bar","owner":"Sophia Martinez","phone":"(305) 373-8866","email":"smartinez@brickellbeauty.com","industry":"Beauty Salon","address":"1000 SE 2nd Ave, Miami FL","notes":"Pitch: Stylists can't answer mid-appointment. AI books new clients all day."},
  {"business":"Aventura Nail Studio","owner":"Linda Pham","phone":"(305) 933-2211","email":"lpham@aventuranails.com","industry":"Beauty Salon","address":"19575 Biscayne Blvd, Aventura FL","notes":"Pitch: Walk-in + call bookings. AI handles phone volume during busy hours."},
  {"business":"Aventura Beauty Lounge","owner":"Sofia Reyes","phone":"(305) 931-8833","email":"sreyes@aventurabeauty.com","industry":"Beauty Salon","address":"2640 Aventura Blvd, Aventura FL","notes":"Pitch: Stylists can't answer mid-service. AI books appointments around the clock."},
  {"business":"South Beach Spa & Wellness","owner":"Camila Reyes","phone":"(305) 534-7733","email":"creyes@sbspawellness.com","industry":"Spa","address":"1420 Ocean Dr, Miami Beach FL","notes":"Pitch: Spa bookings = pure revenue. AI captures every call that comes in."},
  {"business":"Coral Gables Spa Retreat","owner":"Helena Costa","phone":"(305) 441-7744","email":"hcosta@cgspa.com","industry":"Spa","address":"320 Aragon Ave, Coral Gables FL","notes":"Pitch: Spa bookings peak on weekends. AI captures calls when staff is with clients."},
  {"business":"Brickell CrossFit","owner":"Derek Johnson","phone":"(305) 379-5544","email":"djohnson@brickellcrossfit.com","industry":"Fitness","address":"99 SE 5th St, Miami FL","notes":"Pitch: New member inquiries need instant follow-up. AI responds and books trial classes."},
  {"business":"Doral Fitness Club","owner":"Amanda Torres","phone":"(305) 593-8877","email":"atorres@doralfitness.com","industry":"Fitness","address":"8600 NW 36th St, Doral FL","notes":"Pitch: Gym sign-ups are time sensitive. AI answers and converts leads while the front desk is busy."},
  {"business":"Miami Beach Yoga Studio","owner":"Alicia Morgan","phone":"(305) 531-6644","email":"amorgan@mbyoga.com","industry":"Fitness","address":"1680 Meridian Ave, Miami Beach FL","notes":"Pitch: Class bookings and private session requests. AI handles scheduling."},
  {"business":"Brickell Pilates Studio","owner":"Natalie Brooks","phone":"(305) 377-5522","email":"nbrooks@brickellpilates.com","industry":"Fitness","address":"90 SW 3rd St, Miami FL","notes":"Pitch: Boutique studios live on class bookings. AI fills every open slot."},
  {"business":"Doral Martial Arts","owner":"Sensei John Kim","phone":"(305) 592-7766","email":"jkim@doralmartialarts.com","industry":"Fitness","address":"8490 NW 53rd St, Doral FL","notes":"Pitch: Trial class calls are high-intent leads. AI converts them to bookings."},
  {"business":"South Beach Pilates","owner":"Gina Russo","phone":"(305) 534-6644","email":"russo@sbpilates.com","industry":"Fitness","address":"739 Washington Ave, Miami Beach FL","notes":"Pitch: Class scheduling + private sessions. AI books while instructors teach."},
  {"business":"Miami Insurance Group","owner":"Roberto Castillo","phone":"(305) 446-3300","email":"rcastillo@miamins.com","industry":"Insurance","address":"2600 S Douglas Rd, Coral Gables FL","notes":"Pitch: Insurance agents miss quote requests constantly. AI captures and routes every one."},
  {"business":"Biscayne Insurance Agency","owner":"Patricia Gomez","phone":"(305) 891-4455","email":"pgomez@biscayneins.com","industry":"Insurance","address":"1800 NE 123rd St, North Miami FL","notes":"Pitch: AI handles initial quote requests so agents focus on closing."},
  {"business":"North Miami Insurance","owner":"Tom Bradley","phone":"(305) 893-4411","email":"tbradley@nmiins.com","industry":"Insurance","address":"901 NE 125th St, North Miami FL","notes":"Pitch: Insurance shoppers move fast. AI captures leads before they go to a competitor."},
  {"business":"Doral Insurance Agency","owner":"Frank Suarez","phone":"(305) 477-8866","email":"fsuarez@doralins.com","industry":"Insurance","address":"3750 NW 87th Ave, Doral FL","notes":"Pitch: Insurance shoppers need fast quotes. AI captures leads before they move on."},
  {"business":"Coral Gables CPA Group","owner":"Andrew Lee","phone":"(305) 448-7722","email":"alee@cgcpagroup.com","industry":"Accounting","address":"396 Alhambra Cir, Coral Gables FL","notes":"Pitch: Tax season = call surge. AI handles overflow and books consultations."},
  {"business":"Miami Bookkeeping Solutions","owner":"Gloria Mendez","phone":"(305) 774-5500","email":"gmendez@miamibookkeeping.com","industry":"Accounting","address":"8 SE 8th St, Miami FL","notes":"Pitch: Small business accounting clients call constantly. AI manages intake."},
  {"business":"Doral Tax Services","owner":"Rosa Fernandez","phone":"(305) 594-1122","email":"rfernandez@doraltax.com","industry":"Accounting","address":"8181 NW 36th St, Doral FL","notes":"Pitch: Tax prep clients call constantly during season. AI books appointments automatically."},
  {"business":"Brickell Tax Advisory","owner":"Steven Park","phone":"(305) 375-9900","email":"spark@brickelltax.com","industry":"Accounting","address":"888 Brickell Ave, Miami FL","notes":"Pitch: High-net-worth clients expect instant response. AI never misses a call."},
  {"business":"Coral Gables Accounting","owner":"Linda Park","phone":"(305) 446-5500","email":"lpark@cgaccounting.com","industry":"Accounting","address":"2525 Salzedo St, Coral Gables FL","notes":"Pitch: Client calls during busy season overwhelm small CPA firms. AI handles intake."},
  {"business":"Brickell Kitchen","owner":"Chef Marco Silva","phone":"(305) 374-9944","email":"marco@brickellkitchen.com","industry":"Restaurant","address":"801 S Miami Ave, Miami FL","notes":"Pitch: AI takes reservations and catering inquiries — no host needed for phone."},
  {"business":"Coral Gables Bistro","owner":"Jean-Paul Leblanc","phone":"(305) 444-8811","email":"jp@cgbistro.com","industry":"Restaurant","address":"2320 Galiano St, Coral Gables FL","notes":"Pitch: Reservation calls during dinner service kill the vibe. AI handles it."},
  {"business":"Miami Green Landscaping","owner":"Carlos Herrera","phone":"(305) 828-4411","email":"cherrera@miamigreenscape.com","industry":"Landscaping","address":"16851 NW 2nd Ave, Miami FL","notes":"Pitch: Landscaping crews are always in the field. AI answers estimates and scheduling calls."},
  {"business":"South FL Lawn Pros","owner":"Juan Vargas","phone":"(305) 387-6622","email":"jvargas@sflawnpros.com","industry":"Landscaping","address":"12200 SW 8th St, Miami FL","notes":"Pitch: Weekly service routes + new client calls. AI books new accounts automatically."},
  {"business":"Kendall Lawn Care","owner":"Jose Blanco","phone":"(305) 385-5544","email":"jblanco@kendalllawn.com","industry":"Landscaping","address":"9800 SW 77th Ave, Miami FL","notes":"Pitch: Lawn crews in the field all day. AI handles new client calls and schedule changes."},
  {"business":"Brickell Property Management","owner":"Diana Cruz","phone":"(305) 374-4422","email":"dcruz@brickellpm.com","industry":"Property Management","address":"1200 Brickell Bay Dr, Miami FL","notes":"Pitch: Tenant maintenance calls at all hours. AI routes to right team member."},
  {"business":"Coconut Grove Rentals","owner":"Alex Monroe","phone":"(305) 442-3311","email":"amonroe@cgrentals.com","industry":"Property Management","address":"3250 Mary St, Miami FL","notes":"Pitch: Property managers need 24/7 coverage without 24/7 staff. AI delivers it."},
  {"business":"Hialeah Property Management","owner":"Carmen Vega","phone":"(305) 558-7711","email":"cvega@hialeahpm.com","industry":"Property Management","address":"800 E 4th Ave, Hialeah FL","notes":"Pitch: Tenant calls at midnight happen. AI routes to the right person automatically."},
  {"business":"Miami Movers Pro","owner":"Pete Sanchez","phone":"(305) 545-7788","email":"psanchez@miamimoverspro.com","industry":"Moving","address":"2750 NW 79th St, Miami FL","notes":"Pitch: Moving inquiries need instant quotes. AI collects info and books estimates."},
  {"business":"Miami Office Moving","owner":"Tony Greco","phone":"(305) 693-4400","email":"tgreco@miamiofficemoving.com","industry":"Moving","address":"3860 NW 79th Ave, Miami FL","notes":"Pitch: Commercial moving inquiries need fast quotes. AI collects details and schedules estimates."},
  {"business":"Kendall Pest Control","owner":"Dave Willis","phone":"(305) 270-8833","email":"dwillis@kendallpest.com","industry":"Pest Control","address":"12800 SW 88th St, Miami FL","notes":"Pitch: Pest emergencies need same-day response. AI books service visits instantly."},
  {"business":"Miami Cleaning Services","owner":"Rosa Martinez","phone":"(305) 545-2277","email":"rmartinez@miamicleaning.com","industry":"Cleaning","address":"2100 NW 22nd Ave, Miami FL","notes":"Pitch: Cleaning service quotes over the phone = revenue. AI handles all inquiries."},
  {"business":"South Beach Photography","owner":"Alex Turner","phone":"(305) 672-4455","email":"aturner@sbphotography.com","industry":"Photography","address":"1315 Washington Ave, Miami Beach FL","notes":"Pitch: Wedding/event inquiries need fast response. AI books consultations automatically."},
  {"business":"Coconut Grove Florist","owner":"Maria Salazar","phone":"(305) 444-5533","email":"msalazar@cgflorist.com","industry":"Florist","address":"3437 Main Hwy, Miami FL","notes":"Pitch: Event florals need immediate quotes. AI captures every inquiry."},
  {"business":"Hialeah Auto Glass","owner":"Hector Ruiz","phone":"(305) 557-4422","email":"hruiz2@hialeahautoglass2.com","industry":"Auto Repair","address":"3200 W 20th Ave, Hialeah FL","notes":"Pitch: Fast glass replacement calls. AI books same-day visits."},
  {"business":"Aventura Cosmetic Dentistry","owner":"Dr. Rachel Gold","phone":"(305) 931-7700","email":"rgold@aventuracosmeticdent.com","industry":"Dental Office","address":"20801 Biscayne Blvd, Aventura FL","notes":"Pitch: Cosmetic consults are high-value. AI books them before a competitor answers."},
  {"business":"Doral Medical Center","owner":"Dr. Albert Ruiz","phone":"(305) 477-5588","email":"aruiz@doralmed.com","industry":"Medical Office","address":"3650 NW 82nd Ave, Doral FL","notes":"Pitch: Multi-specialty clinic with high call volume. AI routes to right department."},
  {"business":"South Beach Personal Training","owner":"Jake Morris","phone":"(305) 538-4400","email":"jmorris@sbpersonaltraining.com","industry":"Fitness","address":"921 Lincoln Rd, Miami Beach FL","notes":"Pitch: Personal training inquiries are high-intent. AI converts them to booked sessions."},
  {"business":"Miami Lakes Law Group","owner":"Diana Vega","phone":"(305) 820-6611","email":"dvega@mlawgroup.com","industry":"Law Firm","address":"6303 Blue Lagoon Dr, Miami FL","notes":"Pitch: After-hours legal inquiries are often the most urgent. AI captures every one."},
  {"business":"Kendall Spa & Massage","owner":"Christine Wu","phone":"(305) 270-6633","email":"cwu@kendallspa.com","industry":"Spa","address":"11975 N Kendall Dr, Miami FL","notes":"Pitch: Massage bookings are impulse decisions. AI captures them before they move on."},
  {"business":"Brickell Real Estate Co","owner":"Marcus Webb","phone":"(305) 373-1122","email":"mwebb@brickellreco.com","industry":"Real Estate","address":"1001 Brickell Bay Dr, Miami FL","notes":"Pitch: Condo buyer leads have a short window. AI responds immediately."},
  {"business":"North Miami Pest Solutions","owner":"Gary Ross","phone":"(305) 891-7744","email":"gross@nmpestsolutions.com","industry":"Pest Control","address":"12900 NE 8th Ave, North Miami FL","notes":"Pitch: Cockroach/termite calls are urgent. AI books same-day inspection instantly."},
  {"business":"Coral Gables Physical Therapy","owner":"Dr. Nina Patel","phone":"(305) 444-2288","email":"npatel@cgphysicaltherapy.com","industry":"Physical Therapy","address":"201 Alhambra Cir, Coral Gables FL","notes":"Pitch: Referral calls from doctors need immediate pickup. AI captures and books."},
  {"business":"South Miami Insurance","owner":"Ben Carter","phone":"(305) 666-8800","email":"bcarter@southmiamiins.com","industry":"Insurance","address":"6000 S Dixie Hwy, South Miami FL","notes":"Pitch: Insurance shoppers compare 3 agencies. AI ensures you answer first."},
]

for lead in leads:
    lead['id'] = str(uuid.uuid4())
    lead['source'] = 'AI-Generated'
    lead['tags'] = 'ai-generated'
    lead['status'] = 'new'
    lead['method'] = 'phone'

print(f'Generated {len(leads)} leads')

try:
    r = requests.get('https://janovum.com/api/crm/contacts', timeout=10)
    existing = r.json() if r.status_code == 200 else []
    print(f'Existing contacts on CRM: {len(existing)}')
except Exception as e:
    existing = []
    print(f'Could not fetch existing: {e}')

all_contacts = existing + leads
r = requests.post('https://janovum.com/api/crm/contacts', json=all_contacts, timeout=15)
print(f'POST status: {r.status_code} — {r.text[:200]}')
